### ISSUE TITLE
Error 404 in setup

### ISSUE THREAD

**Issue by RodGal-2020** [gulvarol/bsldict#3]
Following the [setup](https://github.com/gulvarol/bsldict#setup) given I get an error 404 while trying to connect to robots.ox.ac.uk, and therefore I can not download either the dataset metadata or the pretrained models.

The error I get is, more precisely:
```
--2022-06-06 09:45:30--  https://www.robots.ox.ac.uk/~vgg/research/bsldict/data/bsldict_v1.pkl%0D
Resolving [www.robots.ox.ac.uk](http://www.robots.ox.ac.uk/) ([www.robots.ox.ac.uk](http://www.robots.ox.ac.uk/))... 129.67.94.2
Connecting to [www.robots.ox.ac.uk](http://www.robots.ox.ac.uk/) ([www.robots.ox.ac.uk)|129.67.94.2|:443](http://www.robots.ox.ac.uk%29%7C129.67.94.2%7C:443/)... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-06-06 11:45:31 ERROR 404: Not Found.
```

The [first link](https://www.robots.ox.ac.uk/~vgg/research/bsldict/data/bsldict_v1.pkl%0D) doesn't work, is there a new link I could use?

Thanks beforehand! :)

**Comment by gulvarol** [comment]
Hi, I could not reproduce the problem from my end. Could you try running directly `wget https://www.robots.ox.ac.uk/~vgg/research/bsldict/data/bsldict_v1.pkl` ? In the link, there seems to be trailing characters `%0D`. Hope that helps.

**Comment by RodGal-2020** [comment]
Yes, using that it worked, thanks!
